apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: arodriguezsemidey
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/arodriguezsemidey-harbor-project/app:971c881-b7bb019
        ports:
        - containerPort: 500
